/**
 * PRIDE Proteomes RESTful web service API
 * For more details and examples please see the <a href=\"/pride/help/proteomes/access/webservice\">additional documentation pages</a>
 *
 * OpenAPI spec version: 1.0
 * Contact: pride-support@ebi.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package uk.ac.ebi.pride.proteomes.web.client;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * Basic statistics about a dataset (e.g. per species)
 */
@ApiModel(description = "Basic statistics about a dataset (e.g. per species)")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-12T09:18:20.547+01:00")
public class DatasetStats   {
  @SerializedName("commonName")
  private String commonName = null;

  @SerializedName("mappedGeneGroupCount")
  private Long mappedGeneGroupCount = null;

  @SerializedName("mappedProteinCount")
  private Long mappedProteinCount = null;

  @SerializedName("peptiformCount")
  private Long peptiformCount = null;

  @SerializedName("scientificName")
  private String scientificName = null;

  @SerializedName("taxid")
  private Integer taxid = null;

  @SerializedName("totalGeneGroupCount")
  private Long totalGeneGroupCount = null;

  @SerializedName("totalProteinCount")
  private Long totalProteinCount = null;

  public DatasetStats commonName(String commonName) {
    this.commonName = commonName;
    return this;
  }

   /**
   * common species name
   * @return commonName
  **/
  @ApiModelProperty(example = "null", value = "common species name")
  public String getCommonName() {
    return commonName;
  }

  public void setCommonName(String commonName) {
    this.commonName = commonName;
  }

  public DatasetStats mappedGeneGroupCount(Long mappedGeneGroupCount) {
    this.mappedGeneGroupCount = mappedGeneGroupCount;
    return this;
  }

   /**
   * number of mapped gene groups in the dataset
   * @return mappedGeneGroupCount
  **/
  @ApiModelProperty(example = "null", value = "number of mapped gene groups in the dataset")
  public Long getMappedGeneGroupCount() {
    return mappedGeneGroupCount;
  }

  public void setMappedGeneGroupCount(Long mappedGeneGroupCount) {
    this.mappedGeneGroupCount = mappedGeneGroupCount;
  }

  public DatasetStats mappedProteinCount(Long mappedProteinCount) {
    this.mappedProteinCount = mappedProteinCount;
    return this;
  }

   /**
   * number of mapped proteins in the dataset
   * @return mappedProteinCount
  **/
  @ApiModelProperty(example = "null", value = "number of mapped proteins in the dataset")
  public Long getMappedProteinCount() {
    return mappedProteinCount;
  }

  public void setMappedProteinCount(Long mappedProteinCount) {
    this.mappedProteinCount = mappedProteinCount;
  }

  public DatasetStats peptiformCount(Long peptiformCount) {
    this.peptiformCount = peptiformCount;
    return this;
  }

   /**
   * number of peptiforms in the dataset
   * @return peptiformCount
  **/
  @ApiModelProperty(example = "null", value = "number of peptiforms in the dataset")
  public Long getPeptiformCount() {
    return peptiformCount;
  }

  public void setPeptiformCount(Long peptiformCount) {
    this.peptiformCount = peptiformCount;
  }

  public DatasetStats scientificName(String scientificName) {
    this.scientificName = scientificName;
    return this;
  }

   /**
   * scientific species name
   * @return scientificName
  **/
  @ApiModelProperty(example = "null", value = "scientific species name")
  public String getScientificName() {
    return scientificName;
  }

  public void setScientificName(String scientificName) {
    this.scientificName = scientificName;
  }

  public DatasetStats taxid(Integer taxid) {
    this.taxid = taxid;
    return this;
  }

   /**
   * species taxon id defining the dataset (1 = all species)
   * @return taxid
  **/
  @ApiModelProperty(example = "null", value = "species taxon id defining the dataset (1 = all species)")
  public Integer getTaxid() {
    return taxid;
  }

  public void setTaxid(Integer taxid) {
    this.taxid = taxid;
  }

  public DatasetStats totalGeneGroupCount(Long totalGeneGroupCount) {
    this.totalGeneGroupCount = totalGeneGroupCount;
    return this;
  }

   /**
   * total of gene groups in the dataset
   * @return totalGeneGroupCount
  **/
  @ApiModelProperty(example = "null", value = "total of gene groups in the dataset")
  public Long getTotalGeneGroupCount() {
    return totalGeneGroupCount;
  }

  public void setTotalGeneGroupCount(Long totalGeneGroupCount) {
    this.totalGeneGroupCount = totalGeneGroupCount;
  }

  public DatasetStats totalProteinCount(Long totalProteinCount) {
    this.totalProteinCount = totalProteinCount;
    return this;
  }

   /**
   * total of proteins in the dataset
   * @return totalProteinCount
  **/
  @ApiModelProperty(example = "null", value = "total of proteins in the dataset")
  public Long getTotalProteinCount() {
    return totalProteinCount;
  }

  public void setTotalProteinCount(Long totalProteinCount) {
    this.totalProteinCount = totalProteinCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetStats datasetStats = (DatasetStats) o;
    return Objects.equals(this.commonName, datasetStats.commonName) &&
        Objects.equals(this.mappedGeneGroupCount, datasetStats.mappedGeneGroupCount) &&
        Objects.equals(this.mappedProteinCount, datasetStats.mappedProteinCount) &&
        Objects.equals(this.peptiformCount, datasetStats.peptiformCount) &&
        Objects.equals(this.scientificName, datasetStats.scientificName) &&
        Objects.equals(this.taxid, datasetStats.taxid) &&
        Objects.equals(this.totalGeneGroupCount, datasetStats.totalGeneGroupCount) &&
        Objects.equals(this.totalProteinCount, datasetStats.totalProteinCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commonName, mappedGeneGroupCount, mappedProteinCount, peptiformCount, scientificName, taxid, totalGeneGroupCount, totalProteinCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetStats {\n");

    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    mappedGeneGroupCount: ").append(toIndentedString(mappedGeneGroupCount)).append("\n");
    sb.append("    mappedProteinCount: ").append(toIndentedString(mappedProteinCount)).append("\n");
    sb.append("    peptiformCount: ").append(toIndentedString(peptiformCount)).append("\n");
    sb.append("    scientificName: ").append(toIndentedString(scientificName)).append("\n");
    sb.append("    taxid: ").append(toIndentedString(taxid)).append("\n");
    sb.append("    totalGeneGroupCount: ").append(toIndentedString(totalGeneGroupCount)).append("\n");
    sb.append("    totalProteinCount: ").append(toIndentedString(totalProteinCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

