/**
 * PRIDE Proteomes RESTful web service API
 * For more details and examples please see the <a href=\"/pride/help/proteomes/access/webservice\">additional documentation pages</a>
 *
 * OpenAPI spec version: 1.0
 * Contact: pride-support@ebi.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package uk.ac.ebi.pride.proteomes.web.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Information about a protein feature
 */
@ApiModel(description = "Information about a protein feature")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-12T09:18:20.547+01:00")
public class Feature   {
  @SerializedName("end")
  private Integer end = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("start")
  private Integer start = null;

  @SerializedName("type")
  private String type = null;

  public Feature end(Integer end) {
    this.end = end;
    return this;
  }

   /**
   * the end position of the feature on the mapped protein
   * @return end
  **/
  @ApiModelProperty(example = "null", value = "the end position of the feature on the mapped protein")
  public Integer getEnd() {
    return end;
  }

  public void setEnd(Integer end) {
    this.end = end;
  }

  public Feature id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Feature start(Integer start) {
    this.start = start;
    return this;
  }

   /**
   * the start position of the feature on the mapped protein
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "the start position of the feature on the mapped protein")
  public Integer getStart() {
    return start;
  }

  public void setStart(Integer start) {
    this.start = start;
  }

  public Feature type(String type) {
    this.type = type;
    return this;
  }

   /**
   * type of the feature (e.g. signal peptide, transmembrane regions...)
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "type of the feature (e.g. signal peptide, transmembrane regions...)")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Feature feature = (Feature) o;
    return Objects.equals(this.end, feature.end) &&
        Objects.equals(this.id, feature.id) &&
        Objects.equals(this.start, feature.start) &&
        Objects.equals(this.type, feature.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(end, id, start, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Feature {\n");
    
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

