/**
 * PRIDE Proteomes RESTful web service API
 * For more details and examples please see the <a href=\"/pride/help/proteomes/access/webservice\">additional documentation pages</a>
 *
 * OpenAPI spec version: 1.0
 * Contact: pride-support@ebi.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package uk.ac.ebi.pride.proteomes.web.client;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * ReleaseSummary
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-12T09:18:20.547+01:00")
public class ReleaseSummary   {
  @SerializedName("numCanonicalProteins")
  private Long numCanonicalProteins = null;

  @SerializedName("numGenes")
  private Long numGenes = null;

  @SerializedName("numIsoformProteins")
  private Long numIsoformProteins = null;

  @SerializedName("numMappedCanonicalProteins")
  private Long numMappedCanonicalProteins = null;

  @SerializedName("numMappedCanonicalProteinsWithUniquePeptides")
  private Long numMappedCanonicalProteinsWithUniquePeptides = null;

  @SerializedName("numMappedGenes")
  private Long numMappedGenes = null;

  @SerializedName("numMappedGenesWithUniquePeptides")
  private Long numMappedGenesWithUniquePeptides = null;

  @SerializedName("numMappedIsoformProteins")
  private Long numMappedIsoformProteins = null;

  @SerializedName("numMappedIsoformProteinsWithUniquePeptides")
  private Long numMappedIsoformProteinsWithUniquePeptides = null;

  @SerializedName("numMappedPeptidesToProteins")
  private Long numMappedPeptidesToProteins = null;

  @SerializedName("numMappedProteinWithEvidencePredicted")
  private Long numMappedProteinWithEvidencePredicted = null;

  @SerializedName("numMappedProteinWithEvidenceUncertain")
  private Long numMappedProteinWithEvidenceUncertain = null;

  @SerializedName("numMappedProteins")
  private Long numMappedProteins = null;

  @SerializedName("numMappedProteinsWithEvidenceInferredByHomology")
  private Long numMappedProteinsWithEvidenceInferredByHomology = null;

  @SerializedName("numMappedProteinsWithEvidenceNotReported")
  private Long numMappedProteinsWithEvidenceNotReported = null;

  @SerializedName("numMappedProteinsWithExpEvidence")
  private Long numMappedProteinsWithExpEvidence = null;

  @SerializedName("numMappedProteinsWithExpEvidenceAtTranscript")
  private Long numMappedProteinsWithExpEvidenceAtTranscript = null;

  @SerializedName("numMappedProteinsWithUniquePeptides")
  private Long numMappedProteinsWithUniquePeptides = null;

  @SerializedName("numMappedUniquePeptidesToCanonicalProteins")
  private Long numMappedUniquePeptidesToCanonicalProteins = null;

  @SerializedName("numMappedUniquePeptidesToGenes")
  private Long numMappedUniquePeptidesToGenes = null;

  @SerializedName("numMappedUniquePeptidesToIsoformProteins")
  private Long numMappedUniquePeptidesToIsoformProteins = null;

  @SerializedName("numMappedUniquePeptidesToProteins")
  private Long numMappedUniquePeptidesToProteins = null;

  @SerializedName("numPeptides")
  private Long numPeptides = null;

  @SerializedName("numPeptiforms")
  private Long numPeptiforms = null;

  @SerializedName("numProteins")
  private Long numProteins = null;

  @SerializedName("numProteinsWithEvidenceInferredByHomology")
  private Long numProteinsWithEvidenceInferredByHomology = null;

  @SerializedName("numProteinsWithEvidenceNotReported")
  private Long numProteinsWithEvidenceNotReported = null;

  @SerializedName("numProteinsWithEvidencePredicted")
  private Long numProteinsWithEvidencePredicted = null;

  @SerializedName("numProteinsWithEvidenceUncertain")
  private Long numProteinsWithEvidenceUncertain = null;

  @SerializedName("numProteinsWithExpEvidence")
  private Long numProteinsWithExpEvidence = null;

  @SerializedName("numProteinsWithExpEvidenceAtTranscript")
  private Long numProteinsWithExpEvidenceAtTranscript = null;

  @SerializedName("referenceDatabase")
  private String referenceDatabase = null;

  @SerializedName("referenceDatabaseVersion")
  private String referenceDatabaseVersion = null;

  @SerializedName("scientificName")
  private String scientificName = null;

  @SerializedName("taxonID")
  private Integer taxonID = null;

  public ReleaseSummary numCanonicalProteins(Long numCanonicalProteins) {
    this.numCanonicalProteins = numCanonicalProteins;
    return this;
  }

   /**
   * Get numCanonicalProteins
   * @return numCanonicalProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumCanonicalProteins() {
    return numCanonicalProteins;
  }

  public void setNumCanonicalProteins(Long numCanonicalProteins) {
    this.numCanonicalProteins = numCanonicalProteins;
  }

  public ReleaseSummary numGenes(Long numGenes) {
    this.numGenes = numGenes;
    return this;
  }

   /**
   * Get numGenes
   * @return numGenes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumGenes() {
    return numGenes;
  }

  public void setNumGenes(Long numGenes) {
    this.numGenes = numGenes;
  }

  public ReleaseSummary numIsoformProteins(Long numIsoformProteins) {
    this.numIsoformProteins = numIsoformProteins;
    return this;
  }

   /**
   * Get numIsoformProteins
   * @return numIsoformProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumIsoformProteins() {
    return numIsoformProteins;
  }

  public void setNumIsoformProteins(Long numIsoformProteins) {
    this.numIsoformProteins = numIsoformProteins;
  }

  public ReleaseSummary numMappedCanonicalProteins(Long numMappedCanonicalProteins) {
    this.numMappedCanonicalProteins = numMappedCanonicalProteins;
    return this;
  }

   /**
   * Get numMappedCanonicalProteins
   * @return numMappedCanonicalProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedCanonicalProteins() {
    return numMappedCanonicalProteins;
  }

  public void setNumMappedCanonicalProteins(Long numMappedCanonicalProteins) {
    this.numMappedCanonicalProteins = numMappedCanonicalProteins;
  }

  public ReleaseSummary numMappedCanonicalProteinsWithUniquePeptides(Long numMappedCanonicalProteinsWithUniquePeptides) {
    this.numMappedCanonicalProteinsWithUniquePeptides = numMappedCanonicalProteinsWithUniquePeptides;
    return this;
  }

   /**
   * Get numMappedCanonicalProteinsWithUniquePeptides
   * @return numMappedCanonicalProteinsWithUniquePeptides
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedCanonicalProteinsWithUniquePeptides() {
    return numMappedCanonicalProteinsWithUniquePeptides;
  }

  public void setNumMappedCanonicalProteinsWithUniquePeptides(Long numMappedCanonicalProteinsWithUniquePeptides) {
    this.numMappedCanonicalProteinsWithUniquePeptides = numMappedCanonicalProteinsWithUniquePeptides;
  }

  public ReleaseSummary numMappedGenes(Long numMappedGenes) {
    this.numMappedGenes = numMappedGenes;
    return this;
  }

   /**
   * Get numMappedGenes
   * @return numMappedGenes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedGenes() {
    return numMappedGenes;
  }

  public void setNumMappedGenes(Long numMappedGenes) {
    this.numMappedGenes = numMappedGenes;
  }

  public ReleaseSummary numMappedGenesWithUniquePeptides(Long numMappedGenesWithUniquePeptides) {
    this.numMappedGenesWithUniquePeptides = numMappedGenesWithUniquePeptides;
    return this;
  }

   /**
   * Get numMappedGenesWithUniquePeptides
   * @return numMappedGenesWithUniquePeptides
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedGenesWithUniquePeptides() {
    return numMappedGenesWithUniquePeptides;
  }

  public void setNumMappedGenesWithUniquePeptides(Long numMappedGenesWithUniquePeptides) {
    this.numMappedGenesWithUniquePeptides = numMappedGenesWithUniquePeptides;
  }

  public ReleaseSummary numMappedIsoformProteins(Long numMappedIsoformProteins) {
    this.numMappedIsoformProteins = numMappedIsoformProteins;
    return this;
  }

   /**
   * Get numMappedIsoformProteins
   * @return numMappedIsoformProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedIsoformProteins() {
    return numMappedIsoformProteins;
  }

  public void setNumMappedIsoformProteins(Long numMappedIsoformProteins) {
    this.numMappedIsoformProteins = numMappedIsoformProteins;
  }

  public ReleaseSummary numMappedIsoformProteinsWithUniquePeptides(Long numMappedIsoformProteinsWithUniquePeptides) {
    this.numMappedIsoformProteinsWithUniquePeptides = numMappedIsoformProteinsWithUniquePeptides;
    return this;
  }

   /**
   * Get numMappedIsoformProteinsWithUniquePeptides
   * @return numMappedIsoformProteinsWithUniquePeptides
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedIsoformProteinsWithUniquePeptides() {
    return numMappedIsoformProteinsWithUniquePeptides;
  }

  public void setNumMappedIsoformProteinsWithUniquePeptides(Long numMappedIsoformProteinsWithUniquePeptides) {
    this.numMappedIsoformProteinsWithUniquePeptides = numMappedIsoformProteinsWithUniquePeptides;
  }

  public ReleaseSummary numMappedPeptidesToProteins(Long numMappedPeptidesToProteins) {
    this.numMappedPeptidesToProteins = numMappedPeptidesToProteins;
    return this;
  }

   /**
   * Get numMappedPeptidesToProteins
   * @return numMappedPeptidesToProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedPeptidesToProteins() {
    return numMappedPeptidesToProteins;
  }

  public void setNumMappedPeptidesToProteins(Long numMappedPeptidesToProteins) {
    this.numMappedPeptidesToProteins = numMappedPeptidesToProteins;
  }

  public ReleaseSummary numMappedProteinWithEvidencePredicted(Long numMappedProteinWithEvidencePredicted) {
    this.numMappedProteinWithEvidencePredicted = numMappedProteinWithEvidencePredicted;
    return this;
  }

   /**
   * Get numMappedProteinWithEvidencePredicted
   * @return numMappedProteinWithEvidencePredicted
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedProteinWithEvidencePredicted() {
    return numMappedProteinWithEvidencePredicted;
  }

  public void setNumMappedProteinWithEvidencePredicted(Long numMappedProteinWithEvidencePredicted) {
    this.numMappedProteinWithEvidencePredicted = numMappedProteinWithEvidencePredicted;
  }

  public ReleaseSummary numMappedProteinWithEvidenceUncertain(Long numMappedProteinWithEvidenceUncertain) {
    this.numMappedProteinWithEvidenceUncertain = numMappedProteinWithEvidenceUncertain;
    return this;
  }

   /**
   * Get numMappedProteinWithEvidenceUncertain
   * @return numMappedProteinWithEvidenceUncertain
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedProteinWithEvidenceUncertain() {
    return numMappedProteinWithEvidenceUncertain;
  }

  public void setNumMappedProteinWithEvidenceUncertain(Long numMappedProteinWithEvidenceUncertain) {
    this.numMappedProteinWithEvidenceUncertain = numMappedProteinWithEvidenceUncertain;
  }

  public ReleaseSummary numMappedProteins(Long numMappedProteins) {
    this.numMappedProteins = numMappedProteins;
    return this;
  }

   /**
   * Get numMappedProteins
   * @return numMappedProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedProteins() {
    return numMappedProteins;
  }

  public void setNumMappedProteins(Long numMappedProteins) {
    this.numMappedProteins = numMappedProteins;
  }

  public ReleaseSummary numMappedProteinsWithEvidenceInferredByHomology(Long numMappedProteinsWithEvidenceInferredByHomology) {
    this.numMappedProteinsWithEvidenceInferredByHomology = numMappedProteinsWithEvidenceInferredByHomology;
    return this;
  }

   /**
   * Get numMappedProteinsWithEvidenceInferredByHomology
   * @return numMappedProteinsWithEvidenceInferredByHomology
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedProteinsWithEvidenceInferredByHomology() {
    return numMappedProteinsWithEvidenceInferredByHomology;
  }

  public void setNumMappedProteinsWithEvidenceInferredByHomology(Long numMappedProteinsWithEvidenceInferredByHomology) {
    this.numMappedProteinsWithEvidenceInferredByHomology = numMappedProteinsWithEvidenceInferredByHomology;
  }

  public ReleaseSummary numMappedProteinsWithEvidenceNotReported(Long numMappedProteinsWithEvidenceNotReported) {
    this.numMappedProteinsWithEvidenceNotReported = numMappedProteinsWithEvidenceNotReported;
    return this;
  }

   /**
   * Get numMappedProteinsWithEvidenceNotReported
   * @return numMappedProteinsWithEvidenceNotReported
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedProteinsWithEvidenceNotReported() {
    return numMappedProteinsWithEvidenceNotReported;
  }

  public void setNumMappedProteinsWithEvidenceNotReported(Long numMappedProteinsWithEvidenceNotReported) {
    this.numMappedProteinsWithEvidenceNotReported = numMappedProteinsWithEvidenceNotReported;
  }

  public ReleaseSummary numMappedProteinsWithExpEvidence(Long numMappedProteinsWithExpEvidence) {
    this.numMappedProteinsWithExpEvidence = numMappedProteinsWithExpEvidence;
    return this;
  }

   /**
   * Get numMappedProteinsWithExpEvidence
   * @return numMappedProteinsWithExpEvidence
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedProteinsWithExpEvidence() {
    return numMappedProteinsWithExpEvidence;
  }

  public void setNumMappedProteinsWithExpEvidence(Long numMappedProteinsWithExpEvidence) {
    this.numMappedProteinsWithExpEvidence = numMappedProteinsWithExpEvidence;
  }

  public ReleaseSummary numMappedProteinsWithExpEvidenceAtTranscript(Long numMappedProteinsWithExpEvidenceAtTranscript) {
    this.numMappedProteinsWithExpEvidenceAtTranscript = numMappedProteinsWithExpEvidenceAtTranscript;
    return this;
  }

   /**
   * Get numMappedProteinsWithExpEvidenceAtTranscript
   * @return numMappedProteinsWithExpEvidenceAtTranscript
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedProteinsWithExpEvidenceAtTranscript() {
    return numMappedProteinsWithExpEvidenceAtTranscript;
  }

  public void setNumMappedProteinsWithExpEvidenceAtTranscript(Long numMappedProteinsWithExpEvidenceAtTranscript) {
    this.numMappedProteinsWithExpEvidenceAtTranscript = numMappedProteinsWithExpEvidenceAtTranscript;
  }

  public ReleaseSummary numMappedProteinsWithUniquePeptides(Long numMappedProteinsWithUniquePeptides) {
    this.numMappedProteinsWithUniquePeptides = numMappedProteinsWithUniquePeptides;
    return this;
  }

   /**
   * Get numMappedProteinsWithUniquePeptides
   * @return numMappedProteinsWithUniquePeptides
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedProteinsWithUniquePeptides() {
    return numMappedProteinsWithUniquePeptides;
  }

  public void setNumMappedProteinsWithUniquePeptides(Long numMappedProteinsWithUniquePeptides) {
    this.numMappedProteinsWithUniquePeptides = numMappedProteinsWithUniquePeptides;
  }

  public ReleaseSummary numMappedUniquePeptidesToCanonicalProteins(Long numMappedUniquePeptidesToCanonicalProteins) {
    this.numMappedUniquePeptidesToCanonicalProteins = numMappedUniquePeptidesToCanonicalProteins;
    return this;
  }

   /**
   * Get numMappedUniquePeptidesToCanonicalProteins
   * @return numMappedUniquePeptidesToCanonicalProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedUniquePeptidesToCanonicalProteins() {
    return numMappedUniquePeptidesToCanonicalProteins;
  }

  public void setNumMappedUniquePeptidesToCanonicalProteins(Long numMappedUniquePeptidesToCanonicalProteins) {
    this.numMappedUniquePeptidesToCanonicalProteins = numMappedUniquePeptidesToCanonicalProteins;
  }

  public ReleaseSummary numMappedUniquePeptidesToGenes(Long numMappedUniquePeptidesToGenes) {
    this.numMappedUniquePeptidesToGenes = numMappedUniquePeptidesToGenes;
    return this;
  }

   /**
   * Get numMappedUniquePeptidesToGenes
   * @return numMappedUniquePeptidesToGenes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedUniquePeptidesToGenes() {
    return numMappedUniquePeptidesToGenes;
  }

  public void setNumMappedUniquePeptidesToGenes(Long numMappedUniquePeptidesToGenes) {
    this.numMappedUniquePeptidesToGenes = numMappedUniquePeptidesToGenes;
  }

  public ReleaseSummary numMappedUniquePeptidesToIsoformProteins(Long numMappedUniquePeptidesToIsoformProteins) {
    this.numMappedUniquePeptidesToIsoformProteins = numMappedUniquePeptidesToIsoformProteins;
    return this;
  }

   /**
   * Get numMappedUniquePeptidesToIsoformProteins
   * @return numMappedUniquePeptidesToIsoformProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedUniquePeptidesToIsoformProteins() {
    return numMappedUniquePeptidesToIsoformProteins;
  }

  public void setNumMappedUniquePeptidesToIsoformProteins(Long numMappedUniquePeptidesToIsoformProteins) {
    this.numMappedUniquePeptidesToIsoformProteins = numMappedUniquePeptidesToIsoformProteins;
  }

  public ReleaseSummary numMappedUniquePeptidesToProteins(Long numMappedUniquePeptidesToProteins) {
    this.numMappedUniquePeptidesToProteins = numMappedUniquePeptidesToProteins;
    return this;
  }

   /**
   * Get numMappedUniquePeptidesToProteins
   * @return numMappedUniquePeptidesToProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumMappedUniquePeptidesToProteins() {
    return numMappedUniquePeptidesToProteins;
  }

  public void setNumMappedUniquePeptidesToProteins(Long numMappedUniquePeptidesToProteins) {
    this.numMappedUniquePeptidesToProteins = numMappedUniquePeptidesToProteins;
  }

  public ReleaseSummary numPeptides(Long numPeptides) {
    this.numPeptides = numPeptides;
    return this;
  }

   /**
   * Get numPeptides
   * @return numPeptides
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumPeptides() {
    return numPeptides;
  }

  public void setNumPeptides(Long numPeptides) {
    this.numPeptides = numPeptides;
  }

  public ReleaseSummary numPeptiforms(Long numPeptiforms) {
    this.numPeptiforms = numPeptiforms;
    return this;
  }

   /**
   * Get numPeptiforms
   * @return numPeptiforms
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumPeptiforms() {
    return numPeptiforms;
  }

  public void setNumPeptiforms(Long numPeptiforms) {
    this.numPeptiforms = numPeptiforms;
  }

  public ReleaseSummary numProteins(Long numProteins) {
    this.numProteins = numProteins;
    return this;
  }

   /**
   * Get numProteins
   * @return numProteins
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumProteins() {
    return numProteins;
  }

  public void setNumProteins(Long numProteins) {
    this.numProteins = numProteins;
  }

  public ReleaseSummary numProteinsWithEvidenceInferredByHomology(Long numProteinsWithEvidenceInferredByHomology) {
    this.numProteinsWithEvidenceInferredByHomology = numProteinsWithEvidenceInferredByHomology;
    return this;
  }

   /**
   * Get numProteinsWithEvidenceInferredByHomology
   * @return numProteinsWithEvidenceInferredByHomology
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumProteinsWithEvidenceInferredByHomology() {
    return numProteinsWithEvidenceInferredByHomology;
  }

  public void setNumProteinsWithEvidenceInferredByHomology(Long numProteinsWithEvidenceInferredByHomology) {
    this.numProteinsWithEvidenceInferredByHomology = numProteinsWithEvidenceInferredByHomology;
  }

  public ReleaseSummary numProteinsWithEvidenceNotReported(Long numProteinsWithEvidenceNotReported) {
    this.numProteinsWithEvidenceNotReported = numProteinsWithEvidenceNotReported;
    return this;
  }

   /**
   * Get numProteinsWithEvidenceNotReported
   * @return numProteinsWithEvidenceNotReported
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumProteinsWithEvidenceNotReported() {
    return numProteinsWithEvidenceNotReported;
  }

  public void setNumProteinsWithEvidenceNotReported(Long numProteinsWithEvidenceNotReported) {
    this.numProteinsWithEvidenceNotReported = numProteinsWithEvidenceNotReported;
  }

  public ReleaseSummary numProteinsWithEvidencePredicted(Long numProteinsWithEvidencePredicted) {
    this.numProteinsWithEvidencePredicted = numProteinsWithEvidencePredicted;
    return this;
  }

   /**
   * Get numProteinsWithEvidencePredicted
   * @return numProteinsWithEvidencePredicted
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumProteinsWithEvidencePredicted() {
    return numProteinsWithEvidencePredicted;
  }

  public void setNumProteinsWithEvidencePredicted(Long numProteinsWithEvidencePredicted) {
    this.numProteinsWithEvidencePredicted = numProteinsWithEvidencePredicted;
  }

  public ReleaseSummary numProteinsWithEvidenceUncertain(Long numProteinsWithEvidenceUncertain) {
    this.numProteinsWithEvidenceUncertain = numProteinsWithEvidenceUncertain;
    return this;
  }

   /**
   * Get numProteinsWithEvidenceUncertain
   * @return numProteinsWithEvidenceUncertain
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumProteinsWithEvidenceUncertain() {
    return numProteinsWithEvidenceUncertain;
  }

  public void setNumProteinsWithEvidenceUncertain(Long numProteinsWithEvidenceUncertain) {
    this.numProteinsWithEvidenceUncertain = numProteinsWithEvidenceUncertain;
  }

  public ReleaseSummary numProteinsWithExpEvidence(Long numProteinsWithExpEvidence) {
    this.numProteinsWithExpEvidence = numProteinsWithExpEvidence;
    return this;
  }

   /**
   * Get numProteinsWithExpEvidence
   * @return numProteinsWithExpEvidence
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumProteinsWithExpEvidence() {
    return numProteinsWithExpEvidence;
  }

  public void setNumProteinsWithExpEvidence(Long numProteinsWithExpEvidence) {
    this.numProteinsWithExpEvidence = numProteinsWithExpEvidence;
  }

  public ReleaseSummary numProteinsWithExpEvidenceAtTranscript(Long numProteinsWithExpEvidenceAtTranscript) {
    this.numProteinsWithExpEvidenceAtTranscript = numProteinsWithExpEvidenceAtTranscript;
    return this;
  }

   /**
   * Get numProteinsWithExpEvidenceAtTranscript
   * @return numProteinsWithExpEvidenceAtTranscript
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getNumProteinsWithExpEvidenceAtTranscript() {
    return numProteinsWithExpEvidenceAtTranscript;
  }

  public void setNumProteinsWithExpEvidenceAtTranscript(Long numProteinsWithExpEvidenceAtTranscript) {
    this.numProteinsWithExpEvidenceAtTranscript = numProteinsWithExpEvidenceAtTranscript;
  }

  public ReleaseSummary referenceDatabase(String referenceDatabase) {
    this.referenceDatabase = referenceDatabase;
    return this;
  }

   /**
   * Get referenceDatabase
   * @return referenceDatabase
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReferenceDatabase() {
    return referenceDatabase;
  }

  public void setReferenceDatabase(String referenceDatabase) {
    this.referenceDatabase = referenceDatabase;
  }

  public ReleaseSummary referenceDatabaseVersion(String referenceDatabaseVersion) {
    this.referenceDatabaseVersion = referenceDatabaseVersion;
    return this;
  }

   /**
   * Get referenceDatabaseVersion
   * @return referenceDatabaseVersion
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReferenceDatabaseVersion() {
    return referenceDatabaseVersion;
  }

  public void setReferenceDatabaseVersion(String referenceDatabaseVersion) {
    this.referenceDatabaseVersion = referenceDatabaseVersion;
  }

  public ReleaseSummary scientificName(String scientificName) {
    this.scientificName = scientificName;
    return this;
  }

   /**
   * the release summary's species (scientific name)
   * @return scientificName
  **/
  @ApiModelProperty(example = "null", value = "the release summary's species (scientific name)")
  public String getScientificName() {
    return scientificName;
  }

  public void setScientificName(String scientificName) {
    this.scientificName = scientificName;
  }

  public ReleaseSummary taxonID(Integer taxonID) {
    this.taxonID = taxonID;
    return this;
  }

   /**
   * the release summary's species (taxon id)
   * @return taxonID
  **/
  @ApiModelProperty(example = "null", value = "the release summary's species (taxon id)")
  public Integer getTaxonID() {
    return taxonID;
  }

  public void setTaxonID(Integer taxonID) {
    this.taxonID = taxonID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReleaseSummary releaseSummary = (ReleaseSummary) o;
    return Objects.equals(this.numCanonicalProteins, releaseSummary.numCanonicalProteins) &&
        Objects.equals(this.numGenes, releaseSummary.numGenes) &&
        Objects.equals(this.numIsoformProteins, releaseSummary.numIsoformProteins) &&
        Objects.equals(this.numMappedCanonicalProteins, releaseSummary.numMappedCanonicalProteins) &&
        Objects.equals(this.numMappedCanonicalProteinsWithUniquePeptides, releaseSummary.numMappedCanonicalProteinsWithUniquePeptides) &&
        Objects.equals(this.numMappedGenes, releaseSummary.numMappedGenes) &&
        Objects.equals(this.numMappedGenesWithUniquePeptides, releaseSummary.numMappedGenesWithUniquePeptides) &&
        Objects.equals(this.numMappedIsoformProteins, releaseSummary.numMappedIsoformProteins) &&
        Objects.equals(this.numMappedIsoformProteinsWithUniquePeptides, releaseSummary.numMappedIsoformProteinsWithUniquePeptides) &&
        Objects.equals(this.numMappedPeptidesToProteins, releaseSummary.numMappedPeptidesToProteins) &&
        Objects.equals(this.numMappedProteinWithEvidencePredicted, releaseSummary.numMappedProteinWithEvidencePredicted) &&
        Objects.equals(this.numMappedProteinWithEvidenceUncertain, releaseSummary.numMappedProteinWithEvidenceUncertain) &&
        Objects.equals(this.numMappedProteins, releaseSummary.numMappedProteins) &&
        Objects.equals(this.numMappedProteinsWithEvidenceInferredByHomology, releaseSummary.numMappedProteinsWithEvidenceInferredByHomology) &&
        Objects.equals(this.numMappedProteinsWithEvidenceNotReported, releaseSummary.numMappedProteinsWithEvidenceNotReported) &&
        Objects.equals(this.numMappedProteinsWithExpEvidence, releaseSummary.numMappedProteinsWithExpEvidence) &&
        Objects.equals(this.numMappedProteinsWithExpEvidenceAtTranscript, releaseSummary.numMappedProteinsWithExpEvidenceAtTranscript) &&
        Objects.equals(this.numMappedProteinsWithUniquePeptides, releaseSummary.numMappedProteinsWithUniquePeptides) &&
        Objects.equals(this.numMappedUniquePeptidesToCanonicalProteins, releaseSummary.numMappedUniquePeptidesToCanonicalProteins) &&
        Objects.equals(this.numMappedUniquePeptidesToGenes, releaseSummary.numMappedUniquePeptidesToGenes) &&
        Objects.equals(this.numMappedUniquePeptidesToIsoformProteins, releaseSummary.numMappedUniquePeptidesToIsoformProteins) &&
        Objects.equals(this.numMappedUniquePeptidesToProteins, releaseSummary.numMappedUniquePeptidesToProteins) &&
        Objects.equals(this.numPeptides, releaseSummary.numPeptides) &&
        Objects.equals(this.numPeptiforms, releaseSummary.numPeptiforms) &&
        Objects.equals(this.numProteins, releaseSummary.numProteins) &&
        Objects.equals(this.numProteinsWithEvidenceInferredByHomology, releaseSummary.numProteinsWithEvidenceInferredByHomology) &&
        Objects.equals(this.numProteinsWithEvidenceNotReported, releaseSummary.numProteinsWithEvidenceNotReported) &&
        Objects.equals(this.numProteinsWithEvidencePredicted, releaseSummary.numProteinsWithEvidencePredicted) &&
        Objects.equals(this.numProteinsWithEvidenceUncertain, releaseSummary.numProteinsWithEvidenceUncertain) &&
        Objects.equals(this.numProteinsWithExpEvidence, releaseSummary.numProteinsWithExpEvidence) &&
        Objects.equals(this.numProteinsWithExpEvidenceAtTranscript, releaseSummary.numProteinsWithExpEvidenceAtTranscript) &&
        Objects.equals(this.referenceDatabase, releaseSummary.referenceDatabase) &&
        Objects.equals(this.referenceDatabaseVersion, releaseSummary.referenceDatabaseVersion) &&
        Objects.equals(this.scientificName, releaseSummary.scientificName) &&
        Objects.equals(this.taxonID, releaseSummary.taxonID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numCanonicalProteins, numGenes, numIsoformProteins, numMappedCanonicalProteins, numMappedCanonicalProteinsWithUniquePeptides, numMappedGenes, numMappedGenesWithUniquePeptides, numMappedIsoformProteins, numMappedIsoformProteinsWithUniquePeptides, numMappedPeptidesToProteins, numMappedProteinWithEvidencePredicted, numMappedProteinWithEvidenceUncertain, numMappedProteins, numMappedProteinsWithEvidenceInferredByHomology, numMappedProteinsWithEvidenceNotReported, numMappedProteinsWithExpEvidence, numMappedProteinsWithExpEvidenceAtTranscript, numMappedProteinsWithUniquePeptides, numMappedUniquePeptidesToCanonicalProteins, numMappedUniquePeptidesToGenes, numMappedUniquePeptidesToIsoformProteins, numMappedUniquePeptidesToProteins, numPeptides, numPeptiforms, numProteins, numProteinsWithEvidenceInferredByHomology, numProteinsWithEvidenceNotReported, numProteinsWithEvidencePredicted, numProteinsWithEvidenceUncertain, numProteinsWithExpEvidence, numProteinsWithExpEvidenceAtTranscript, referenceDatabase, referenceDatabaseVersion, scientificName, taxonID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReleaseSummary {\n");

    sb.append("    numCanonicalProteins: ").append(toIndentedString(numCanonicalProteins)).append("\n");
    sb.append("    numGenes: ").append(toIndentedString(numGenes)).append("\n");
    sb.append("    numIsoformProteins: ").append(toIndentedString(numIsoformProteins)).append("\n");
    sb.append("    numMappedCanonicalProteins: ").append(toIndentedString(numMappedCanonicalProteins)).append("\n");
    sb.append("    numMappedCanonicalProteinsWithUniquePeptides: ").append(toIndentedString(numMappedCanonicalProteinsWithUniquePeptides)).append("\n");
    sb.append("    numMappedGenes: ").append(toIndentedString(numMappedGenes)).append("\n");
    sb.append("    numMappedGenesWithUniquePeptides: ").append(toIndentedString(numMappedGenesWithUniquePeptides)).append("\n");
    sb.append("    numMappedIsoformProteins: ").append(toIndentedString(numMappedIsoformProteins)).append("\n");
    sb.append("    numMappedIsoformProteinsWithUniquePeptides: ").append(toIndentedString(numMappedIsoformProteinsWithUniquePeptides)).append("\n");
    sb.append("    numMappedPeptidesToProteins: ").append(toIndentedString(numMappedPeptidesToProteins)).append("\n");
    sb.append("    numMappedProteinWithEvidencePredicted: ").append(toIndentedString(numMappedProteinWithEvidencePredicted)).append("\n");
    sb.append("    numMappedProteinWithEvidenceUncertain: ").append(toIndentedString(numMappedProteinWithEvidenceUncertain)).append("\n");
    sb.append("    numMappedProteins: ").append(toIndentedString(numMappedProteins)).append("\n");
    sb.append("    numMappedProteinsWithEvidenceInferredByHomology: ").append(toIndentedString(numMappedProteinsWithEvidenceInferredByHomology)).append("\n");
    sb.append("    numMappedProteinsWithEvidenceNotReported: ").append(toIndentedString(numMappedProteinsWithEvidenceNotReported)).append("\n");
    sb.append("    numMappedProteinsWithExpEvidence: ").append(toIndentedString(numMappedProteinsWithExpEvidence)).append("\n");
    sb.append("    numMappedProteinsWithExpEvidenceAtTranscript: ").append(toIndentedString(numMappedProteinsWithExpEvidenceAtTranscript)).append("\n");
    sb.append("    numMappedProteinsWithUniquePeptides: ").append(toIndentedString(numMappedProteinsWithUniquePeptides)).append("\n");
    sb.append("    numMappedUniquePeptidesToCanonicalProteins: ").append(toIndentedString(numMappedUniquePeptidesToCanonicalProteins)).append("\n");
    sb.append("    numMappedUniquePeptidesToGenes: ").append(toIndentedString(numMappedUniquePeptidesToGenes)).append("\n");
    sb.append("    numMappedUniquePeptidesToIsoformProteins: ").append(toIndentedString(numMappedUniquePeptidesToIsoformProteins)).append("\n");
    sb.append("    numMappedUniquePeptidesToProteins: ").append(toIndentedString(numMappedUniquePeptidesToProteins)).append("\n");
    sb.append("    numPeptides: ").append(toIndentedString(numPeptides)).append("\n");
    sb.append("    numPeptiforms: ").append(toIndentedString(numPeptiforms)).append("\n");
    sb.append("    numProteins: ").append(toIndentedString(numProteins)).append("\n");
    sb.append("    numProteinsWithEvidenceInferredByHomology: ").append(toIndentedString(numProteinsWithEvidenceInferredByHomology)).append("\n");
    sb.append("    numProteinsWithEvidenceNotReported: ").append(toIndentedString(numProteinsWithEvidenceNotReported)).append("\n");
    sb.append("    numProteinsWithEvidencePredicted: ").append(toIndentedString(numProteinsWithEvidencePredicted)).append("\n");
    sb.append("    numProteinsWithEvidenceUncertain: ").append(toIndentedString(numProteinsWithEvidenceUncertain)).append("\n");
    sb.append("    numProteinsWithExpEvidence: ").append(toIndentedString(numProteinsWithExpEvidence)).append("\n");
    sb.append("    numProteinsWithExpEvidenceAtTranscript: ").append(toIndentedString(numProteinsWithExpEvidenceAtTranscript)).append("\n");
    sb.append("    referenceDatabase: ").append(toIndentedString(referenceDatabase)).append("\n");
    sb.append("    referenceDatabaseVersion: ").append(toIndentedString(referenceDatabaseVersion)).append("\n");
    sb.append("    scientificName: ").append(toIndentedString(scientificName)).append("\n");
    sb.append("    taxonID: ").append(toIndentedString(taxonID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

