/**
 * PRIDE Proteomes RESTful web service API
 * For more details and examples please see the <a href=\"/pride/help/proteomes/access/webservice\">additional documentation pages</a>
 *
 * OpenAPI spec version: 1.0
 * Contact: pride-support@ebi.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package uk.ac.ebi.pride.proteomes.web.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import uk.ac.ebi.pride.proteomes.web.client.ReleaseSummary;


/**
 * ReleaseSummaryList
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-12T09:18:20.547+01:00")
public class ReleaseSummaryList   {
  @SerializedName("releaseSummaryList")
  private List<ReleaseSummary> releaseSummaryList = new ArrayList<ReleaseSummary>();

  public ReleaseSummaryList releaseSummaryList(List<ReleaseSummary> releaseSummaryList) {
    this.releaseSummaryList = releaseSummaryList;
    return this;
  }

   /**
   * Get releaseSummaryList
   * @return releaseSummaryList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ReleaseSummary> getReleaseSummaryList() {
    return releaseSummaryList;
  }

  public void setReleaseSummaryList(List<ReleaseSummary> releaseSummaryList) {
    this.releaseSummaryList = releaseSummaryList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReleaseSummaryList releaseSummaryList = (ReleaseSummaryList) o;
    return Objects.equals(this.releaseSummaryList, releaseSummaryList.releaseSummaryList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(releaseSummaryList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReleaseSummaryList {\n");
    
    sb.append("    releaseSummaryList: ").append(toIndentedString(releaseSummaryList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

