/**
 * PRIDE Proteomes RESTful web service API
 * For more details and examples please see the <a href=\"/pride/help/proteomes/access/webservice\">additional documentation pages</a>
 *
 * OpenAPI spec version: 1.0
 * Contact: pride-support@ebi.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package uk.ac.ebi.pride.proteomes.web.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import uk.ac.ebi.pride.proteomes.web.client.DatasetStats;


/**
 * Basic statistics PRIDE Proteomes data
 */
@ApiModel(description = "Basic statistics PRIDE Proteomes data")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-12T09:18:20.547+01:00")
public class Statistics   {
  @SerializedName("datasetStatistics")
  private List<DatasetStats> datasetStatistics = new ArrayList<DatasetStats>();

  @SerializedName("speciesCount")
  private Integer speciesCount = null;

  public Statistics datasetStatistics(List<DatasetStats> datasetStatistics) {
    this.datasetStatistics = datasetStatistics;
    return this;
  }

   /**
   * list of statistics for each species (e.g. dataset)
   * @return datasetStatistics
  **/
  @ApiModelProperty(example = "null", value = "list of statistics for each species (e.g. dataset)")
  public List<DatasetStats> getDatasetStatistics() {
    return datasetStatistics;
  }

  public void setDatasetStatistics(List<DatasetStats> datasetStatistics) {
    this.datasetStatistics = datasetStatistics;
  }

  public Statistics speciesCount(Integer speciesCount) {
    this.speciesCount = speciesCount;
    return this;
  }

   /**
   * total species (e.g. dataset) count in Proteomes
   * @return speciesCount
  **/
  @ApiModelProperty(example = "null", value = "total species (e.g. dataset) count in Proteomes")
  public Integer getSpeciesCount() {
    return speciesCount;
  }

  public void setSpeciesCount(Integer speciesCount) {
    this.speciesCount = speciesCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Statistics statistics = (Statistics) o;
    return Objects.equals(this.datasetStatistics, statistics.datasetStatistics) &&
        Objects.equals(this.speciesCount, statistics.speciesCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasetStatistics, speciesCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Statistics {\n");
    
    sb.append("    datasetStatistics: ").append(toIndentedString(datasetStatistics)).append("\n");
    sb.append("    speciesCount: ").append(toIndentedString(speciesCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

