/**
 * PRIDE Proteomes RESTful web service API
 * For more details and examples please see the <a href=\"/pride/help/proteomes/access/webservice\">additional documentation pages</a>
 *
 * OpenAPI spec version: 1.0
 * Contact: pride-support@ebi.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package uk.ac.ebi.pride.proteomes.web;

import uk.ac.ebi.pride.proteomes.web.ApiException;
import uk.ac.ebi.pride.proteomes.web.client.PeptideList;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PeptidecontrollerApi
 */
public class PeptidecontrollerApiTest {

    private final PeptidecontrollerApi api = new PeptidecontrollerApi();

    
    /**
     * getById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByIdUsingGET1Test() throws ApiException {
        String sequence = null;
        Integer species = null;
        String tissue = null;
        String mod = null;
        Boolean includeDetails = null;
        // PeptideList response = api.getByIdUsingGET1(sequence, species, tissue, mod, includeDetails);

        // TODO: test validations
    }
    
    /**
     * getPeptideListForProtein
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPeptideListForProteinUsingGET1Test() throws ApiException {
        String acc = null;
        String tissue = null;
        String mod = null;
        // PeptideList response = api.getPeptideListForProteinUsingGET1(acc, tissue, mod);

        // TODO: test validations
    }
    
    /**
     * getPeptideList
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPeptideListUsingGETTest() throws ApiException {
        Integer species = null;
        String tissue = null;
        String mod = null;
        Integer page = null;
        Integer pageSize = null;
        // PeptideList response = api.getPeptideListUsingGET(species, tissue, mod, page, pageSize);

        // TODO: test validations
    }
    
}
