/**
 * PRIDE Proteomes RESTful web service API
 * For more details and examples please see the <a href=\"/pride/help/proteomes/access/webservice\">additional documentation pages</a>
 *
 * OpenAPI spec version: 1.0
 * Contact: pride-support@ebi.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package uk.ac.ebi.pride.proteomes.web;

import uk.ac.ebi.pride.proteomes.web.ApiException;
import uk.ac.ebi.pride.proteomes.web.client.Protein;
import uk.ac.ebi.pride.proteomes.web.client.ProteinList;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProteincontrollerApi
 */
public class ProteincontrollerApiTest {

    private final ProteincontrollerApi api = new ProteincontrollerApi();

    
    /**
     * getById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByIdUsingGET3Test() throws ApiException {
        String id = null;
        Boolean includeDetails = null;
        // Protein response = api.getByIdUsingGET3(id, includeDetails);

        // TODO: test validations
    }
    
    /**
     * getProteinCount
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProteinCountUsingGET1Test() throws ApiException {
        String species = null;
        String tissue = null;
        String mod = null;
        // Long response = api.getProteinCountUsingGET1(species, tissue, mod);

        // TODO: test validations
    }
    
    /**
     * getProteinListForPeptide
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProteinListForPeptideUsingGETTest() throws ApiException {
        String sequence = null;
        Integer species = null;
        Boolean includeSequence = null;
        // ProteinList response = api.getProteinListForPeptideUsingGET(sequence, species, includeSequence);

        // TODO: test validations
    }
    
    /**
     * getProteinList
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProteinListUsingGET1Test() throws ApiException {
        String species = null;
        String tissue = null;
        String mod = null;
        Boolean includeSequence = null;
        Integer page = null;
        Integer pageSize = null;
        // ProteinList response = api.getProteinListUsingGET1(species, tissue, mod, includeSequence, page, pageSize);

        // TODO: test validations
    }
    
}
