/**
 * PRIDE Proteomes RESTful web service API
 * For more details and examples please see the <a href=\"/pride/help/proteomes/access/webservice\">additional documentation pages</a>
 *
 * OpenAPI spec version: 1.0
 * Contact: pride-support@ebi.ac.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package uk.ac.ebi.pride.proteomes.web;

import uk.ac.ebi.pride.proteomes.web.ApiException;
import uk.ac.ebi.pride.proteomes.web.client.ProteinGroup;
import uk.ac.ebi.pride.proteomes.web.client.ProteinGroupList;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProteingroupcontrollerApi
 */
public class ProteingroupcontrollerApiTest {

    private final ProteingroupcontrollerApi api = new ProteingroupcontrollerApi();

    
    /**
     * getById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByIdUsingGET4Test() throws ApiException {
        String id = null;
        Boolean uniquePeptides = null;
        // ProteinGroup response = api.getByIdUsingGET4(id, uniquePeptides);

        // TODO: test validations
    }
    
    /**
     * getProteinGroupListForProtein
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProteinGroupListForProteinUsingGETTest() throws ApiException {
        String acc = null;
        // ProteinGroupList response = api.getProteinGroupListForProteinUsingGET(acc);

        // TODO: test validations
    }
    
    /**
     * getProteinGroupList
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProteinGroupListUsingGET1Test() throws ApiException {
        Integer species = null;
        Integer page = null;
        Integer pageSize = null;
        // ProteinGroupList response = api.getProteinGroupListUsingGET1(species, page, pageSize);

        // TODO: test validations
    }
    
}
